/**
 * AIPartMesh — loads a per-part GLB (generated by generate-part-mesh) and
 * snaps it to a target anchor on the car, auto-fitting it to a target size
 * box so a Meshy mesh of arbitrary scale lands at the right place.
 *
 * Per-kind fitment rules live here (target world-size + orientation tweaks)
 * so the Meshy output — which has no consistent scale or facing — looks
 * right on top of the user's STL without manual fiddling.
 */
import { useEffect, useMemo, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three-stdlib";

interface FitConfig {
  /** Target world size box (metres) — mesh is uniformly scaled to fit longest edge. */
  targetSize: { x: number; y: number; z: number };
  /** Extra Y rotation in radians (after auto-orient). */
  yawOffset?: number;
  /** Vertical offset applied AFTER fitting (metres) so the mesh sits at the anchor's logical attachment point rather than its centre. */
  yOffset?: number;
}

const FIT_BY_KIND: Record<string, FitConfig> = {
  // Wing: ~1.4m wide, ~0.4m tall, ~0.35m chord. Anchor is the wing centre.
  wing: { targetSize: { x: 0.35, y: 0.4, z: 1.4 }, yOffset: 0 },
  splitter: { targetSize: { x: 0.18, y: 0.05, z: 1.6 }, yOffset: 0.02 },
  diffuser: { targetSize: { x: 0.55, y: 0.12, z: 1.4 }, yOffset: 0.02 },
};

interface Props {
  url: string;
  kind: string;
  position: [number, number, number];
}

export function AIPartMesh({ url, kind, position }: Props) {
  const [scene, setScene] = useState<THREE.Object3D | null>(null);
  const fit = FIT_BY_KIND[kind] ?? { targetSize: { x: 0.5, y: 0.5, z: 0.5 } };

  useEffect(() => {
    let cancelled = false;
    const loader = new GLTFLoader();
    loader.load(
      url,
      (gltf) => {
        if (cancelled) return;
        const root = gltf.scene;

        // Auto-fit: compute bbox, scale uniformly so the longest target axis matches
        // the corresponding mesh axis. This keeps proportions intact while landing
        // the part at the right rough size.
        const box = new THREE.Box3().setFromObject(root);
        const size = new THREE.Vector3();
        box.getSize(size);

        // Pick the dominant scaling axis (whichever target dim is biggest relative
        // to the matching mesh dim). For a wing this naturally lands as width-driven.
        const sx = fit.targetSize.x / Math.max(size.x, 0.001);
        const sy = fit.targetSize.y / Math.max(size.y, 0.001);
        const sz = fit.targetSize.z / Math.max(size.z, 0.001);
        const scale = Math.min(sx, sy, sz); // fit-inside, never exceed target box
        root.scale.setScalar(scale);

        // Re-centre after scaling so the mesh's centre lands at the anchor.
        const box2 = new THREE.Box3().setFromObject(root);
        const centre = new THREE.Vector3();
        box2.getCenter(centre);
        root.position.sub(centre);

        // Apply per-kind y offset (e.g. lift wing so it doesn't bury into deck).
        if (fit.yOffset) root.position.y += fit.yOffset;

        // Cast/receive shadows + sane material if Meshy gave us nothing.
        root.traverse((c) => {
          const m = c as THREE.Mesh;
          if (m.isMesh) {
            m.castShadow = true;
            m.receiveShadow = true;
          }
        });

        setScene(root);
      },
      undefined,
      (err) => {
        console.warn("AIPartMesh load failed:", url, err);
      },
    );
    return () => { cancelled = true; };
  }, [url, kind, fit.targetSize.x, fit.targetSize.y, fit.targetSize.z, fit.yOffset]);

  if (!scene) return null;
  return (
    <group position={position} rotation={[0, fit.yawOffset ?? 0, 0]}>
      <primitive object={scene} />
    </group>
  );
}
